variables:
  API_TOKEN: $TEST_DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR'
  API_PATH: ''
  OUTPUT_PATH: 'out'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
  only:
    - ci-test
